const portfolioData = { 
    contact: { 
        email: "abdulrhman.abdulghaffar001@gmail.com", 
        linkedin: "https://www.linkedin.com/in/AbdulRhmanAbdulGhaffar", 
        github: "https://github.com/AbdulRhmanAbdulGhaffar", 
        medium: "https://medium.com/@aboodi_abdo" 
    },
    en: {
        text: { 
            name_short: "AbdulRhman AbdulGhaffar", 
            nav_about: "About", 
            nav_expertise: "Expertise", 
            nav_projects: "Projects", 
            nav_articles: "Articles",
            nav_contact: "Contact", 
            hero_greeting: "Hi, I'm AbdulRhman AbdulGhaffar", 
            hero_role: ["Cyber Security Specialist", "Incident Response Analyst", "System Administration"], 
            hero_cta: "View My Work", 
            about_title: "About Me", 
            about_view_cv: "View CV", 
            stats_experience: "Years of Experience", 
            stats_projects: "Projects Completed", 
            stats_certs: "Certifications Earned", 
            stats_tools: "Tools Mastered", 
            expertise_title: "Areas of Expertise", 
            experience_title: "Professional Experience", 
            skills_title: "Technical Arsenal", 
            certifications_title: "Certifications & Training", 
            projects_title: "Featured Projects", 
            articles_title: "My Articles",
            articles_follow_me: "To follow my articles and latest developments, connect with me on:",
            contact_title: "Initiate Contact", 
            contact_desc: "I'm actively seeking new opportunities. If you have a project or a role where my skills can add value, let's connect and build a more secure future.", 
            contact_form_name: "Your Name / Alias", 
            contact_form_email: "Your Secure Email", 
            contact_form_message: "Your Encrypted Message", 
            contact_form_send: "Transmit Securely", 
            contact_form_success: "Transmission successful. I will respond shortly.", 
            project_filter_all: "All", 
            project_link_text: "Access Project" 
        },
        objective: "A highly motivated Incident Response Analyst, specializing in rapid threat detection, forensic analysis, and decisive incident containment. I leverage cutting-edge SIEM solutions and proactive threat hunting to fortify digital defenses and ensure unwavering operational resilience against sophisticated cyber threats.",
        about: "As a cyber sentinel, I am passionate about the art of digital defense. My expertise lies in navigating the complex landscape of cybersecurity threats. With a background in SOC operations and hands-on experience in threat hunting and log analysis with tools like Splunk and Wazuh, I am adept at identifying, neutralizing, and dissecting security incidents. I am a lifelong learner, committed to staying ahead of the curve in the ever-evolving theater of cyber warfare.",
        stats: [ { value: "1+", label_en: "Year of Experience" }, { value: "10+", label_en: "Completed Projects" }, { value: "15+", label_en: "Certifications" }, { value: "15+", label_en: "Tools Mastered" } ],
        expertise: [ { icon: "fas fa-shield-virus", title: "Threat Detection & Analysis", description: "Utilizing SIEM tools and log analysis to identify, triage, and investigate potential security threats in real-time." }, { icon: "fas fa-fire-extinguisher", title: "Incident Containment & Eradication", description: "Applying structured response methodologies to contain threats, minimize impact, and eradicate malicious actors from the network." }, { icon: "fas fa-microscope", title: "Digital Forensics", description: "Conducting basic memory, disk, and volatile data analysis to uncover attack vectors and gather critical evidence." } ],
        experience: [ { title: "Incident Response Analyst Trainee", company: "DEPI Egypt", date: "Jul 2025 - Dec 2025", duties: ["Engaged in an intensive 6-month cybersecurity program, specializing in incident response.", "Contributed to the 'Smart Intrusion Detection System' project, focusing on rule tuning and alert analysis.", "Applied modern incident response playbooks in simulated cyber-attack scenarios."],}, { title: "Trainer", company: "TOP Academy", date: "Jan 2023 - Jan 2024", duties: ["Delivered training for Python and Microsoft IC3, enhancing students' technical competencies.", "Developed practical labs and exercises to prepare students for certification exams."],}, { title: "Data Center Maintenance", company: "Delta Higher Institute", date: "Aug 2024", duties: ["Participated in data center maintenance activities, including system updates and hardware inspections.", "Assisted in infrastructure configuration to ensure optimal performance and security."],}, ],
        skills: [ "Splunk", "IBM QRadar", "Wazuh", "MITRE ATT&CK", "Threat Hunting", "Memory Forensics", "Disk Forensics", "Python", "Bash", "TCP/IP", "Firewalls", "VPNs", "Linux", "Windows Server", "TryHackMe"],
        certifications: [
            { name: "Incident Response Analyst", issuer: "DEPI, Egypt", training: "AMIT", logo: "https://i.postimg.cc/Sxy0s9QS/download-3.png", noFilter: true },
            { name: "Certified Incident Responder", issuer: "eLearnSecurity", training: "Netriders", logo: "https://i.postimg.cc/w3YpFbdL/download-1.png", noFilter: true },
            { name: "SEC504 – GCIH", issuer: "SANS Institute", training: "Netriders", logo: "https://i.postimg.cc/w3YpFbdL/download-1.png", noFilter: true },
            { name: "SEC450 – GSOC", issuer: "SANS Institute", training: "Netriders", logo: "https://i.postimg.cc/w3YpFbdL/download-1.png", noFilter: true },
            { name: "Security+ SY0-601", issuer: "CompTIA", training: "Netriders", logo: "https://i.postimg.cc/w3YpFbdL/download-1.png", noFilter: true },
            { name: "Linux System Administrator", issuer: "Red Hat", training: "NTI, Egypt", logo: "https://i.postimg.cc/Rhryz6bz/download-6.png", noFilter: true },
            { name: "Network Engineer Trainee", issuer: "Cisco", training: "NTI, Egypt", logo: "https://upload.wikimedia.org/wikipedia/commons/6/64/Cisco_logo.svg" },
            { name: "HCIA – Datacom", issuer: "Huawei", training: "NTI, Egypt", logo: "https://i.postimg.cc/Znpk9FyR/download.jpg", noFilter: true },
            { name: "HCIA – CloudComputing", issuer: "Huawei", training: "NTI, Egypt", logo: "https://i.postimg.cc/Znpk9FyR/download.jpg", noFilter: true },
            { name: "Microsoft Certified Solutions Associate", issuer: "Microsoft", training: "Delta Academy", logo: "https://i.postimg.cc/6pxSPv4V/microsoft.png", noFilter: true },
            { name: "IT Technical Support Specialist", issuer: "DEPI, Egypt", training: "globalknowledge", logo: "https://i.postimg.cc/Sxy0s9QS/download-3.png", noFilter: true },
            { name: "Pre Security", issuer: "TryHackMe", training: "TryHackMe", logo: "https://i.postimg.cc/VLkBkLQy/download-7.png", noFilter: true },
            { name: "Cyber Security 101", issuer: "TryHackMe", training: "TryHackMe", logo: "https://i.postimg.cc/VLkBkLQy/download-7.png", noFilter: true },
            { name: "SOC Tier 1", issuer: "TryHackMe", training: "TryHackMe", logo: "https://i.postimg.cc/VLkBkLQy/download-7.png", noFilter: true },
            { name: "SOC Tier 2", issuer: "TryHackMe", training: "TryHackMe", logo: "https://i.postimg.cc/VLkBkLQy/download-7.png", noFilter: true },
        ],
        projects: [
            { title: "Vulnerability Assessment and Remediation Plan", description: "Developed a comprehensive vulnerability assessment and remediation plan for DEPI's network infrastructure as part of a capstone project.", image: "https://placehold.co/600x400/0A2F3A/0DF7F7?text=VA+Plan", tags: ["Vulnerability Assessment", "Cybersecurity", "DEPI"], link: "#",},
            { title: "Smart Intrusion Detection System", description: "A collaborative project focused on developing and implementing an advanced IDS. My role involved analyzing network traffic and fine-tuning detection rules.", image: "https://placehold.co/600x400/0A2F3A/0DF7F7?text=IDS+Project", tags: ["IDS/IPS", "Threat Detection", "Analysis"], link: "#",},
            { title: "SOC Simulation Labs", description: "Completed multiple hands-on labs on TryHackMe simulating a SOC environment, investigating alerts and performing log analysis with Splunk.", image: "https://placehold.co/600x400/0A2F3A/0DF7F7?text=SOC+Labs", tags: ["SIEM", "Splunk", "Log Analysis"], link: "#",},
            { title: "Network Troubleshooting Automation", description: "Developed Python and Bash scripts to automate common network diagnostic tasks, such as ping sweeps and port scanning.", image: "https://placehold.co/600x400/0A2F3A/0DF7F7?text=Automation", tags: ["Automation", "Python", "Bash"], link: "#",},
        ],
    },
    ar: {
        // Arabic translations can be added here in the same structure
    }
};